[package]
name = "native"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
liblog-sys = { path = "./liblog-sys" }
jni = { default-features = false, version = "*" }
